name: dotnet

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore dotnet

    - name: Build
      run: dotnet build dotnet --no-restore --configuration Release

    - name: Test
      run: dotnet test dotnet --no-build  --configuration Release --verbosity normal

    - name: Artifact
      uses: actions/upload-artifact@v2
      with:
        name: PlantBook.nupkg
        path: dotnet/PlantBook/bin/**/*.nupkg
